version: '3.8'

services:
  rinkeby:
    image: shardlabs/go-ethereum-sourcify:1.10.3
    container_name: geth-rinkeby
    env_file: .env
    command: --syncmode full --snapshot=false --rinkeby
    volumes:
      - type: bind
        source: /home/gather/geth_data/4/.ethereum
        target: /root/.ethereum
    networks:
      - geth

networks:
  geth:

volumes:
  rinkeby: