version: '3.8'

services:
  mainnet:
    image: shardlabs/go-ethereum-sourcify:1.10.3
    container_name: geth-mainnet
    env_file: .env
    command: --syncmode full --snapshot=false
    volumes:
      - type: bind
        source: /home/gather/geth_data/1/.ethereum
        target: /root/.ethereum
    networks:
      - geth

networks:
  mainnet:

volumes:
  mainnet: