version: '3.8'

services:
  node:
    image: shardlabs/go-ethereum-sourcify:stable
    container_name: geth-mainnet
    ports: 
      - 8545:8545
    env_file: .env
    command: --syncmode full --snapshot=false
    volumes:
      - type: bind
        source: /home/gather/geth_data/1/.ethereum
        target: /root/.ethereum
    networks:
      - geth

networks:
  geth:

volumes:
  geth: