version: '3.8'

services:
  goerli:
    image: shardlabs/go-ethereum-sourcify:test
    container_name: geth-goerli
    env_file: .env
    command: --syncmode full --snapshot=false --goerli
    volumes:
      - type: bind
        source: /home/gather/geth_data/5/.ethereum
        target: /root/.ethereum
    networks:
      - geth

networks:
  geth:

volumes:
  goerli: