version: '3.8'

services:
  ropsten:
    image: shardlabs/go-ethereum-sourcify:1.10.4
    container_name: geth-ropsten
    env_file: .env
    command: --syncmode full --snapshot=false --ropsten --http --http.api personal,eth,net,web3 --http.addr 0.0.0.0
    ports:
      - "8543:8545"
    volumes:
      - type: bind
        source: /home/gather/geth_data/3/.ethereum
        target: /root/.ethereum
    networks:
      - geth

networks:
  geth:

volumes:
  ropsten: