version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - geth
    restart: always


networks:
  geth: